/*
User API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package demo4api2sdk

import (
	"encoding/json"
)

// checks if the ServicesIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicesIdPutRequest{}

// ServicesIdPutRequest struct for ServicesIdPutRequest
type ServicesIdPutRequest struct {
	Name *string `json:"name,omitempty"`
	Price *float32 `json:"price,omitempty"`
}

// NewServicesIdPutRequest instantiates a new ServicesIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesIdPutRequest() *ServicesIdPutRequest {
	this := ServicesIdPutRequest{}
	return &this
}

// NewServicesIdPutRequestWithDefaults instantiates a new ServicesIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesIdPutRequestWithDefaults() *ServicesIdPutRequest {
	this := ServicesIdPutRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ServicesIdPutRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesIdPutRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ServicesIdPutRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ServicesIdPutRequest) SetName(v string) {
	o.Name = &v
}

// GetPrice returns the Price field value if set, zero value otherwise.
func (o *ServicesIdPutRequest) GetPrice() float32 {
	if o == nil || IsNil(o.Price) {
		var ret float32
		return ret
	}
	return *o.Price
}

// GetPriceOk returns a tuple with the Price field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesIdPutRequest) GetPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.Price) {
		return nil, false
	}
	return o.Price, true
}

// HasPrice returns a boolean if a field has been set.
func (o *ServicesIdPutRequest) HasPrice() bool {
	if o != nil && !IsNil(o.Price) {
		return true
	}

	return false
}

// SetPrice gets a reference to the given float32 and assigns it to the Price field.
func (o *ServicesIdPutRequest) SetPrice(v float32) {
	o.Price = &v
}

func (o ServicesIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicesIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Price) {
		toSerialize["price"] = o.Price
	}
	return toSerialize, nil
}

type NullableServicesIdPutRequest struct {
	value *ServicesIdPutRequest
	isSet bool
}

func (v NullableServicesIdPutRequest) Get() *ServicesIdPutRequest {
	return v.value
}

func (v *NullableServicesIdPutRequest) Set(val *ServicesIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesIdPutRequest(val *ServicesIdPutRequest) *NullableServicesIdPutRequest {
	return &NullableServicesIdPutRequest{value: val, isSet: true}
}

func (v NullableServicesIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


