/*
User API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package demo4api2sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServicesPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicesPostRequest{}

// ServicesPostRequest struct for ServicesPostRequest
type ServicesPostRequest struct {
	Name string `json:"name"`
	Price float32 `json:"price"`
}

type _ServicesPostRequest ServicesPostRequest

// NewServicesPostRequest instantiates a new ServicesPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesPostRequest(name string, price float32) *ServicesPostRequest {
	this := ServicesPostRequest{}
	this.Name = name
	this.Price = price
	return &this
}

// NewServicesPostRequestWithDefaults instantiates a new ServicesPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesPostRequestWithDefaults() *ServicesPostRequest {
	this := ServicesPostRequest{}
	return &this
}

// GetName returns the Name field value
func (o *ServicesPostRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServicesPostRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServicesPostRequest) SetName(v string) {
	o.Name = v
}

// GetPrice returns the Price field value
func (o *ServicesPostRequest) GetPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *ServicesPostRequest) GetPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *ServicesPostRequest) SetPrice(v float32) {
	o.Price = v
}

func (o ServicesPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicesPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["price"] = o.Price
	return toSerialize, nil
}

func (o *ServicesPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"price",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServicesPostRequest := _ServicesPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServicesPostRequest)

	if err != nil {
		return err
	}

	*o = ServicesPostRequest(varServicesPostRequest)

	return err
}

type NullableServicesPostRequest struct {
	value *ServicesPostRequest
	isSet bool
}

func (v NullableServicesPostRequest) Get() *ServicesPostRequest {
	return v.value
}

func (v *NullableServicesPostRequest) Set(val *ServicesPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesPostRequest(val *ServicesPostRequest) *NullableServicesPostRequest {
	return &NullableServicesPostRequest{value: val, isSet: true}
}

func (v NullableServicesPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


