/*
User API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package demo4api2sdk

import (
	"encoding/json"
)

// checks if the NetworksIdPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworksIdPutRequest{}

// NetworksIdPutRequest struct for NetworksIdPutRequest
type NetworksIdPutRequest struct {
	Name *string `json:"name,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewNetworksIdPutRequest instantiates a new NetworksIdPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworksIdPutRequest() *NetworksIdPutRequest {
	this := NetworksIdPutRequest{}
	return &this
}

// NewNetworksIdPutRequestWithDefaults instantiates a new NetworksIdPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworksIdPutRequestWithDefaults() *NetworksIdPutRequest {
	this := NetworksIdPutRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *NetworksIdPutRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworksIdPutRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *NetworksIdPutRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *NetworksIdPutRequest) SetName(v string) {
	o.Name = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *NetworksIdPutRequest) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworksIdPutRequest) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *NetworksIdPutRequest) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *NetworksIdPutRequest) SetUrl(v string) {
	o.Url = &v
}

func (o NetworksIdPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworksIdPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableNetworksIdPutRequest struct {
	value *NetworksIdPutRequest
	isSet bool
}

func (v NullableNetworksIdPutRequest) Get() *NetworksIdPutRequest {
	return v.value
}

func (v *NullableNetworksIdPutRequest) Set(val *NetworksIdPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworksIdPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworksIdPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworksIdPutRequest(val *NetworksIdPutRequest) *NullableNetworksIdPutRequest {
	return &NullableNetworksIdPutRequest{value: val, isSet: true}
}

func (v NullableNetworksIdPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworksIdPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


