/*
User API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package demo4api2sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UsersPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UsersPostRequest{}

// UsersPostRequest struct for UsersPostRequest
type UsersPostRequest struct {
	Name string `json:"name"`
	Email string `json:"email"`
}

type _UsersPostRequest UsersPostRequest

// NewUsersPostRequest instantiates a new UsersPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUsersPostRequest(name string, email string) *UsersPostRequest {
	this := UsersPostRequest{}
	this.Name = name
	this.Email = email
	return &this
}

// NewUsersPostRequestWithDefaults instantiates a new UsersPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUsersPostRequestWithDefaults() *UsersPostRequest {
	this := UsersPostRequest{}
	return &this
}

// GetName returns the Name field value
func (o *UsersPostRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UsersPostRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UsersPostRequest) SetName(v string) {
	o.Name = v
}

// GetEmail returns the Email field value
func (o *UsersPostRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *UsersPostRequest) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *UsersPostRequest) SetEmail(v string) {
	o.Email = v
}

func (o UsersPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UsersPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

func (o *UsersPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUsersPostRequest := _UsersPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUsersPostRequest)

	if err != nil {
		return err
	}

	*o = UsersPostRequest(varUsersPostRequest)

	return err
}

type NullableUsersPostRequest struct {
	value *UsersPostRequest
	isSet bool
}

func (v NullableUsersPostRequest) Get() *UsersPostRequest {
	return v.value
}

func (v *NullableUsersPostRequest) Set(val *UsersPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUsersPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUsersPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUsersPostRequest(val *UsersPostRequest) *NullableUsersPostRequest {
	return &NullableUsersPostRequest{value: val, isSet: true}
}

func (v NullableUsersPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUsersPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


