/*
User API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package demo4api2sdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NetworksPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworksPostRequest{}

// NetworksPostRequest struct for NetworksPostRequest
type NetworksPostRequest struct {
	Name string `json:"name"`
	Url string `json:"url"`
}

type _NetworksPostRequest NetworksPostRequest

// NewNetworksPostRequest instantiates a new NetworksPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworksPostRequest(name string, url string) *NetworksPostRequest {
	this := NetworksPostRequest{}
	this.Name = name
	this.Url = url
	return &this
}

// NewNetworksPostRequestWithDefaults instantiates a new NetworksPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworksPostRequestWithDefaults() *NetworksPostRequest {
	this := NetworksPostRequest{}
	return &this
}

// GetName returns the Name field value
func (o *NetworksPostRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *NetworksPostRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *NetworksPostRequest) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *NetworksPostRequest) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *NetworksPostRequest) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *NetworksPostRequest) SetUrl(v string) {
	o.Url = v
}

func (o NetworksPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworksPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *NetworksPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNetworksPostRequest := _NetworksPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNetworksPostRequest)

	if err != nil {
		return err
	}

	*o = NetworksPostRequest(varNetworksPostRequest)

	return err
}

type NullableNetworksPostRequest struct {
	value *NetworksPostRequest
	isSet bool
}

func (v NullableNetworksPostRequest) Get() *NetworksPostRequest {
	return v.value
}

func (v *NullableNetworksPostRequest) Set(val *NetworksPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworksPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworksPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworksPostRequest(val *NetworksPostRequest) *NullableNetworksPostRequest {
	return &NullableNetworksPostRequest{value: val, isSet: true}
}

func (v NullableNetworksPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworksPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


